"""中英术语对照表：让中文提问也能命中英文教材。

知识库里 `books/` 全是英文教材，而检索走的是稀疏倒排索引——**按词匹配**。
「二叉树」和 "binary search tree" 在词表上没有任何交集，中文提问打到英文书上
就是 0 分。这里维护一份领域术语对照，检索时自动把查询里的中文术语补上对应的
英文词（反向也支持），英文教材才有机会被选中。

加词就往 TERMS 里添一行：中文写法 -> (英文词, ...)。

英文词**按单个单词写**：建索引时英文也是被切开成单词的，写成词组反而匹配不上
（想覆盖 "low power" 就写 ("low", "power")，别写 ("low power",)）。
同理带连字符/撇号的也拆开：two's complement 写成 ("two", "complement")。
"""
import re

TERMS = {
    # ---------- 算法与数据结构 ----------
    "数据结构": ("data", "structure"),
    "算法": ("algorithm",),
    "数组": ("array",),
    "链表": ("linked", "list"),
    "单链表": ("singly", "linked", "list"),
    "双向链表": ("doubly", "linked", "list"),
    "循环链表": ("circular", "linked", "list"),
    "栈": ("stack",),
    "队列": ("queue",),
    "双端队列": ("deque",),
    "哈希表": ("hash", "table"),
    "散列表": ("hash", "table"),
    "哈希": ("hash", "hashing"),
    "堆": ("heap",),
    "优先队列": ("priority", "queue"),
    "二叉树": ("binary", "tree"),
    "二叉搜索树": ("binary", "search", "tree"),
    "二叉查找树": ("binary", "search", "tree"),
    "平衡二叉树": ("balanced", "binary", "tree"),
    "红黑树": ("red", "black", "tree"),
    "线段树": ("segment", "tree"),
    "字典树": ("trie",),
    "前缀树": ("trie",),
    "并查集": ("disjoint", "set", "union"),
    "图": ("graph",),
    "有向图": ("directed", "graph"),
    "无向图": ("undirected", "graph"),
    "加权图": ("weighted", "graph"),
    "邻接矩阵": ("adjacency", "matrix"),
    "邻接表": ("adjacency", "list"),
    "深度优先": ("depth", "first", "search"),
    "广度优先": ("breadth", "first", "search"),
    "最短路径": ("shortest", "path"),
    "最小生成树": ("minimum", "spanning", "tree"),
    "拓扑排序": ("topological", "sort"),
    "强连通分量": ("strongly", "connected", "component"),
    "网络流": ("network", "flow"),
    "二分查找": ("binary", "search"),
    "二分答案": ("binary", "search"),
    "排序": ("sorting", "sort"),
    "快速排序": ("quick", "sort"),
    "归并排序": ("merge", "sort"),
    "堆排序": ("heap", "sort"),
    "插入排序": ("insertion", "sort"),
    "冒泡排序": ("bubble", "sort"),
    "选择排序": ("selection", "sort"),
    "计数排序": ("counting", "sort"),
    "基数排序": ("radix", "sort"),
    "桶排序": ("bucket", "sort"),
    "递归": ("recursion", "recursive"),
    "迭代": ("iteration", "iterative"),
    "分治": ("divide", "conquer"),
    "动态规划": ("dynamic", "programming"),
    "记忆化": ("memoization", "memoized"),
    "状态转移": ("transition", "recurrence"),
    "贪心": ("greedy",),
    "回溯": ("backtracking", "backtrack"),
    "剪枝": ("pruning", "prune"),
    "枚举": ("enumeration", "brute", "force"),
    "字符串": ("string",),
    "模式匹配": ("pattern", "matching"),
    "后缀数组": ("suffix", "array"),
    "后缀自动机": ("suffix", "automaton"),
    "时间复杂度": ("time", "complexity"),
    "空间复杂度": ("space", "complexity"),
    "渐进分析": ("asymptotic", "analysis"),
    "摊还分析": ("amortized", "analysis"),
    "上界": ("upper", "bound"),
    "下界": ("lower", "bound"),
    "遍历": ("traversal", "traverse"),
    "中序遍历": ("inorder", "traversal"),
    "前序遍历": ("preorder", "traversal"),
    "后序遍历": ("postorder", "traversal"),
    "层序遍历": ("level", "order", "traversal"),
    "平衡因子": ("balance", "factor"),
    "旋转": ("rotation", "rotate"),
    "叶子节点": ("leaf", "node"),
    "根节点": ("root", "node"),
    "指针": ("pointer",),
    "引用": ("reference",),
    "原地": ("in", "place"),
    "稳定排序": ("stable", "sort"),
    "去重": ("duplicate", "unique"),
    "前缀和": ("prefix", "sum"),
    "差分": ("difference", "array"),
    "滑动窗口": ("sliding", "window"),
    "双指针": ("two", "pointers"),
    "位运算": ("bit", "operation"),
    "位掩码": ("bitmask", "mask"),

    # ---------- 计算机组成原理 ----------
    "计算机组成原理": ("computer", "organization"),
    "计算机体系结构": ("computer", "architecture"),
    "冯诺依曼": ("von", "neumann"),
    "哈佛结构": ("harvard", "architecture"),
    "指令": ("instruction",),
    "指令集": ("instruction", "set"),
    "指令周期": ("instruction", "cycle"),
    "机器周期": ("machine", "cycle"),
    "时钟周期": ("clock", "cycle"),
    "时钟频率": ("clock", "frequency"),
    "汇编": ("assembly", "assembler"),
    "操作码": ("opcode",),
    "操作数": ("operand",),
    "寻址方式": ("addressing", "mode"),
    "立即数": ("immediate",),
    "寄存器": ("register",),
    "程序计数器": ("program", "counter"),
    "指令寄存器": ("instruction", "register"),
    "累加器": ("accumulator",),
    "算术逻辑单元": ("arithmetic", "logic", "unit"),
    "控制单元": ("control", "unit"),
    "数据通路": ("datapath", "data", "path"),
    "流水线": ("pipeline", "pipelining"),
    "流水线冒险": ("hazard",),
    "数据冒险": ("data", "hazard"),
    "控制冒险": ("control", "hazard"),
    "分支预测": ("branch", "prediction"),
    "转发": ("forwarding",),
    "停顿": ("stall",),
    "乱序执行": ("out", "order", "execution"),
    "超标量": ("superscalar",),
    "缓存": ("cache",),
    "高速缓存": ("cache",),
    "命中率": ("hit", "rate"),
    "缓存未命中": ("cache", "miss"),
    "写回": ("write", "back"),
    "写直达": ("write", "through"),
    "主存": ("main", "memory"),
    "内存": ("memory",),
    "虚拟内存": ("virtual", "memory"),
    "分页": ("paging", "page"),
    "页表": ("page", "table"),
    "缺页": ("page", "fault"),
    "地址空间": ("address", "space"),
    "物理地址": ("physical", "address"),
    "逻辑地址": ("logical", "address"),
    "字节序": ("byte", "order"),
    "大端": ("big", "endian"),
    "小端": ("little", "endian"),
    "总线": ("bus",),
    "数据总线": ("data", "bus"),
    "地址总线": ("address", "bus"),
    "控制总线": ("control", "bus"),
    "中断": ("interrupt",),
    "异常": ("exception",),
    "中断向量": ("interrupt", "vector"),
    "中断处理": ("interrupt", "handler"),
    "直接内存访问": ("direct", "memory", "access"),
    "输入输出": ("input", "output"),
    "内存映射": ("memory", "mapped"),
    "只读存储器": ("read", "only", "memory"),
    "随机存储器": ("random", "access", "memory"),
    "静态随机存储器": ("static", "random", "access", "memory"),
    "动态随机存储器": ("dynamic", "random", "access", "memory"),
    "闪存": ("flash", "memory"),
    "硬盘": ("disk", "drive"),
    "磁盘": ("disk",),
    "扇区": ("sector",),
    "磁道": ("track",),
    "补码": ("two", "complement"),
    "原码": ("sign", "magnitude"),
    "反码": ("one", "complement"),
    "浮点数": ("floating", "point"),
    "定点数": ("fixed", "point"),
    "规格化": ("normalized", "normalization"),
    "舍入": ("rounding", "round"),
    "溢出": ("overflow", "underflow"),
    "位": ("bit",),
    "字节": ("byte",),
    "字长": ("word", "length"),
    "奇偶校验": ("parity", "check"),
    "汉明码": ("hamming", "code"),
    "纠错码": ("error", "correcting", "code"),
    "微程序": ("microprogram", "microcode"),
    "硬布线": ("hardwired",),
    "性能": ("performance",),
    "吞吐量": ("throughput",),
    "延迟": ("latency",),
    "加速比": ("speedup",),
    "摩尔定律": ("moore", "law"),

    # ---------- 嵌入式系统 / 单片机 ----------
    "嵌入式系统": ("embedded", "system"),
    "嵌入式": ("embedded",),
    "单片机": ("microcontroller",),
    "微控制器": ("microcontroller",),
    "实时系统": ("real", "time", "system"),
    "实时操作系统": ("real", "time", "operating", "system"),
    "裸机": ("bare", "metal"),
    "固件": ("firmware",),
    "引导程序": ("bootloader", "boot"),
    "外设": ("peripheral",),
    "通用输入输出": ("general", "purpose", "input", "output"),
    "复用功能": ("alternate", "function"),
    "定时器": ("timer",),
    "计数器": ("counter",),
    "预分频": ("prescaler", "prescale"),
    "自动重装载": ("auto", "reload"),
    "脉宽调制": ("pulse", "width", "modulation"),
    "占空比": ("duty", "cycle"),
    "模数转换": ("analog", "digital", "converter"),
    "数模转换": ("digital", "analog", "converter"),
    "采样": ("sampling", "sample"),
    "分辨率": ("resolution",),
    "基准电压": ("reference", "voltage"),
    "串口": ("serial", "port"),
    "串行通信": ("serial", "communication"),
    "波特率": ("baud", "rate"),
    "异步": ("asynchronous", "async"),
    "同步": ("synchronous", "sync"),
    "通用同步异步收发器": ("universal", "synchronous", "asynchronous", "receiver", "transmitter"),
    "串行外设接口": ("serial", "peripheral", "interface"),
    "集成电路总线": ("inter", "integrated", "circuit"),
    "控制器局域网": ("controller", "area", "network"),
    "看门狗": ("watchdog",),
    "复位": ("reset",),
    "上电复位": ("power", "on", "reset"),
    "时钟树": ("clock", "tree"),
    "晶振": ("crystal", "oscillator"),
    "锁相环": ("phase", "locked", "loop"),
    "内部时钟": ("internal", "clock"),
    "外部时钟": ("external", "clock"),
    "低功耗": ("low", "power"),
    "睡眠模式": ("sleep", "mode"),
    "待机模式": ("standby", "mode"),
    "停机模式": ("stop", "mode"),
    "唤醒": ("wakeup", "wake"),
    "中断优先级": ("interrupt", "priority"),
    "嵌套中断": ("nested", "interrupt"),
    "中断服务程序": ("interrupt", "service", "routine"),
    "轮询": ("polling", "poll"),
    "直接存储器访问": ("direct", "memory", "access"),
    "寄存器映射": ("register", "map"),
    "位带": ("bit", "banding"),
    "状态寄存器": ("status", "register"),
    "控制寄存器": ("control", "register"),
    "数据寄存器": ("data", "register"),
    "堆栈": ("stack", "pointer"),
    "任务调度": ("task", "scheduling"),
    "调度器": ("scheduler",),
    "信号量": ("semaphore",),
    "互斥锁": ("mutex",),
    "消息队列": ("message", "queue"),
    "有限状态机": ("finite", "state", "machine"),
    "状态机": ("state", "machine"),
    "传感器": ("sensor",),
    "执行器": ("actuator",),
    "舵机": ("servo",),
    "步进电机": ("stepper", "motor"),
    "编码器": ("encoder",),
    "脉宽": ("pulse", "width"),
    "按键消抖": ("debounce", "debouncing"),
    "硬件抽象层": ("hardware", "abstraction", "layer"),
    "板级支持包": ("board", "support", "package"),
    "驱动": ("driver",),
    "调试器": ("debugger", "debug"),
    "仿真器": ("emulator", "simulator"),
    "在线调试": ("in", "circuit", "debugging"),
    "烧录": ("flash", "programming"),

    # ---------- 物联网 ----------
    "物联网": ("internet", "things"),
    "万物互联": ("internet", "things"),
    "边缘计算": ("edge", "computing"),
    "云计算": ("cloud", "computing"),
    "雾计算": ("fog", "computing"),
    "网关": ("gateway",),
    "节点": ("node",),
    "设备": ("device",),
    "感知层": ("perception", "layer"),
    "网络层": ("network", "layer"),
    "应用层": ("application", "layer"),
    "参考架构": ("reference", "architecture"),
    "架构": ("architecture",),
    "互操作": ("interoperability", "interoperable"),
    "语义": ("semantic", "semantics"),
    "本体": ("ontology",),
    "数据模型": ("data", "model"),
    "服务发现": ("service", "discovery"),
    "消息队列遥测传输": ("message", "queuing", "telemetry", "transport"),
    "受限应用协议": ("constrained", "application", "protocol"),
    "超文本传输协议": ("hypertext", "transfer", "protocol"),
    "无线传感器网络": ("wireless", "sensor", "network"),
    "射频识别": ("radio", "frequency", "identification"),
    "近场通信": ("near", "field", "communication"),
    "低功耗蓝牙": ("bluetooth", "low", "energy"),
    "紫蜂": ("zigbee",),
    "远距离无线电": ("long", "range"),
    "窄带物联网": ("narrowband", "internet", "things"),
    "蜂窝网络": ("cellular",),
    "第五代移动通信": ("fifth", "generation"),
    "标识": ("identifier", "identification"),
    "身份认证": ("authentication", "authenticate"),
    "授权": ("authorization",),
    "访问控制": ("access", "control"),
    "隐私": ("privacy",),
    "安全": ("security", "secure"),
    "加密": ("encryption", "encrypt"),
    "密钥": ("key",),
    "证书": ("certificate",),
    "信任": ("trust",),
    "威胁": ("threat",),
    "漏洞": ("vulnerability",),
    "攻击": ("attack",),
    "数据采集": ("data", "acquisition"),
    "遥测": ("telemetry",),
    "数字孪生": ("digital", "twin"),
    "智能制造": ("smart", "manufacturing"),
    "智慧城市": ("smart", "city"),
    "可扩展性": ("scalability", "scalable"),
    "异构": ("heterogeneous",),
    "标准化": ("standardization", "standard"),

    # ---------- 数字取证 ----------
    "数字取证": ("digital", "forensics", "forensic"),
    "电子数据取证": ("digital", "evidence", "forensic"),
    "计算机取证": ("computer", "forensics"),
    "取证": ("forensic", "forensics"),
    "证据": ("evidence",),
    "电子证据": ("digital", "evidence"),
    "物证": ("physical", "evidence"),
    "采集": ("acquisition", "acquire"),
    "固定": ("preservation", "preserve"),
    "保全": ("preservation",),
    "完整性": ("integrity",),
    "校验和": ("checksum",),
    "摘要": ("digest",),
    "镜像": ("image", "imaging"),
    "磁盘镜像": ("disk", "image"),
    "内存镜像": ("memory", "image", "dump"),
    "写保护": ("write", "blocker", "protected"),
    "只读": ("read", "only"),
    "链条监管": ("chain", "custody"),
    "证据链": ("chain", "custody"),
    "可采性": ("admissibility", "admissible"),
    "内存取证": ("memory", "forensics"),
    "易失性": ("volatile",),
    "非易失性": ("non", "volatile"),
    "手机取证": ("mobile", "device", "forensics"),
    "移动设备": ("mobile", "device"),
    "提取": ("extraction", "extract"),
    "抽取": ("extraction",),
    "逻辑提取": ("logical", "extraction"),
    "物理提取": ("physical", "extraction"),
    "分析": ("analysis", "analyze"),
    "关联分析": ("correlation",),
    "时间线": ("timeline",),
    "时间戳": ("timestamp",),
    "元数据": ("metadata",),
    "文件系统": ("file", "system"),
    "分区": ("partition",),
    "未分配空间": ("unallocated", "space"),
    "空闲空间": ("slack", "space"),
    "文件雕复": ("file", "carving"),
    "数据恢复": ("data", "recovery", "recover"),
    "已删除": ("deleted", "delete"),
    "隐藏": ("hidden", "hide"),
    "加密卷": ("encrypted", "volume"),
    "解密": ("decryption", "decrypt"),
    "口令": ("password", "passphrase"),
    "反取证": ("anti", "forensics"),
    "隐写": ("steganography", "steganographic"),
    "日志": ("log", "logging"),
    "审计": ("audit",),
    "入侵检测": ("intrusion", "detection"),
    "恶意软件": ("malware",),
    "木马": ("trojan",),
    "病毒": ("virus",),
    "勒索软件": ("ransomware",),
    "钓鱼": ("phishing",),
    "网络取证": ("network", "forensics"),
    "云取证": ("cloud", "forensics"),
    "事件响应": ("incident", "response"),
    "应急响应": ("incident", "response"),
    "调查": ("investigation", "investigate"),
    "报告": ("report", "reporting"),
    "深伪": ("deepfake", "deepfakes"),
    "伪造": ("forgery", "forged"),
    "篡改": ("tampering", "tamper"),
    "真实性": ("authenticity", "authentic"),
    "生物特征": ("biometric", "biometrics"),
    "人脸识别": ("face", "recognition"),
    "指纹": ("fingerprint",),
    "图像取证": ("image", "forensics"),
    "视频取证": ("video", "forensics"),
    "编解码": ("codec", "encoding"),
    "哈希算法": ("hash", "algorithm"),
    "国家标准与技术研究院": ("national", "institute", "standards", "technology"),
    "检验": ("examination", "examine"),
    "鉴定": ("examination", "identification"),
    "证物": ("exhibit",),
    "嫌疑人": ("suspect",),
    "取证工具": ("forensic", "tool", "toolkit"),

    # ---------- 编程语言 / 工程通用 ----------
    "编译": ("compile", "compiler", "compilation"),
    "编译器": ("compiler",),
    "链接": ("link", "linker", "linking"),
    "源代码": ("source", "code"),
    "头文件": ("header", "file"),
    "库函数": ("library", "function"),
    "标准库": ("standard", "library"),
    "模板": ("template",),
    "泛型": ("generic",),
    "面向对象": ("object", "oriented"),
    "封装": ("encapsulation",),
    "继承": ("inheritance", "inherit"),
    "多态": ("polymorphism",),
    "重载": ("overload", "overloading"),
    "重写": ("override", "overriding"),
    "构造函数": ("constructor",),
    "析构函数": ("destructor",),
    "内存泄漏": ("memory", "leak"),
    "野指针": ("dangling", "pointer"),
    "缓冲区溢出": ("buffer", "overflow"),
    "越界": ("out", "bounds"),
    "断言": ("assert", "assertion"),
    "异常处理": ("exception", "handling"),
    "调试": ("debug", "debugging"),
    "断点": ("breakpoint",),
    "单元测试": ("unit", "test", "testing"),
    "版本控制": ("version", "control"),
    "接口": ("interface",),
    "进程": ("process",),
    "线程": ("thread",),
    "并发": ("concurrency", "concurrent"),
    "死锁": ("deadlock",),
    "同步锁": ("lock", "mutex"),
    "编码": ("encoding", "encode"),
    "解码": ("decoding", "decode"),
    "二进制": ("binary",),
    "十六进制": ("hexadecimal", "hex"),
}


def _segment(text):
    """跟建索引时同一套切词规则（jieba），保证补出来的词能跟索引里的词对上。"""
    import jieba

    return [t for t in jieba.lcut(text) if t.strip() and any(c.isalnum() for c in t)]


# 英文单词 -> 中文术语，由 TERMS 反推，供「英文提问补中文词」用
_REVERSE = {}
for _cn, _ens in TERMS.items():
    for _en in _ens:
        _REVERSE.setdefault(_en, []).append(_cn)


def expand(text):
    """找出查询里的术语，返回要额外补进检索词表的同义词。

    中文术语用**子串命中**来找，不依赖分词结果——分词可能把「二叉搜索树」切成
    「二叉 / 搜索 / 树」，逐词查表就漏了。命中多个时丢掉被更长术语包含的那些，
    免得「树」这种短词把一批无关的词带进来。
    """
    if not text:
        return []

    matched = sorted((cn for cn in TERMS if len(cn) > 1 and cn in text), key=len, reverse=True)
    kept = []
    for cn in matched:
        if not any(cn in longer for longer in kept):
            kept.append(cn)

    extra = []
    for cn in kept:
        extra.extend(TERMS[cn])  # 中文 -> 英文词

    for word in re.findall(r"[A-Za-z][A-Za-z0-9+#.]*", text):
        for cn in _REVERSE.get(word.lower(), ()):
            extra.extend(_segment(cn))  # 英文 -> 中文词

    seen = set()
    result = []
    for token in extra:
        if token not in seen:
            seen.add(token)
            result.append(token)
    return result